# nacos 配置
#nacos:
#  config:
#    namespace: dev
#    server-addr: http://172.20.10.2:8848/nacos
#    username: dev
#    password: dev



# 加了nacos后下面配置可在nacos中配置 start-------------------
#server:
#  port: 8081
#
## springboot 整合 mybatis 相关配置
#spring:
#  datasource:
#    driver: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: Mark
#    password: 123456
#  aop:
#    proxy-target-class: true # 切换动态代理方式 默认为true
#  boot:
#    admin:
#      client:
#        url: http://localhost:8888 # 配置 Admin Server 地址

# 加了nacos后下面配置可在nacos中配置 end-------------------

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration # 禁用redis自动配置（只要引用了redis依赖就会默认启动redis）
spring:
  profiles:
    active: dev #指定配置文件

#  redis:
#    port: 6379 #redis端口号
#    host: 127.0.0.1 #redis服务器ip地址

mybatis:
  mapper-locations:  classpath:mapper/*Mapper.xml,classpath:mapper/*/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.mark.Models # 配置那个包下的类有默认的别名


management:
  endpoints:
    enabled-by-default: true #启用所有端点
    web:
      exposure:
        include: "*" # 暴露所有端点
        #exclude: "env,beans"
  endpoint:
    health:
      show-details: always #展示所有健康信息
#thymeleaf:
#  cache: false
#  prefix: classpath:/templates   #1.本是默认的地址一般不要加 第一次问题去掉就成功了     2.如果需要加 最后面不要加/
#  suffix: .html
#  check-template-location: true
#  check-template: true

#关闭mybatis-plus的banner图标
mybatis-plus:
  global-config:
    banner: false





